// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QUIZ_GAME_WEB.Data;

#nullable disable

namespace QUIZ_GAME_WEB.Migrations
{
    [DbContext(typeof(QuizGameContext))]
    [Migration("20251130120902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VaiTroID")
                        .HasColumnType("int");

                    b.HasKey("AdminID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.HasIndex("VaiTroID");

                    b.ToTable("Admin", (string)null);

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            NgayTao = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6636),
                            TrangThai = true,
                            UserID = 1,
                            VaiTroID = 1
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.CaiDatNguoiDung", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingID"));

                    b.Property<bool>("AmThanh")
                        .HasColumnType("bit");

                    b.Property<string>("NgonNgu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("NhacNen")
                        .HasColumnType("bit");

                    b.Property<bool>("ThongBao")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SettingID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("CaiDatNguoiDung", (string)null);

                    b.HasData(
                        new
                        {
                            SettingID = 1,
                            AmThanh = true,
                            NgonNgu = "vi",
                            NhacNen = false,
                            ThongBao = true,
                            UserID = 2
                        },
                        new
                        {
                            SettingID = 2,
                            AmThanh = true,
                            NgonNgu = "vi",
                            NhacNen = true,
                            ThongBao = true,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.ClientKey", b =>
                {
                    b.Property<int>("ClientKeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientKeyID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenUngDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientKeyID");

                    b.ToTable("ClientKeys");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "superadmin@quiz.com",
                            HoTen = "Nguyễn Super Admin",
                            MatKhau = "hashed_sa_password",
                            NgayDangKy = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6578),
                            TenDangNhap = "admin_sa",
                            TrangThai = true
                        },
                        new
                        {
                            UserID = 2,
                            Email = "player01@quiz.com",
                            HoTen = "Trần Văn A",
                            MatKhau = "hashed_p1_password",
                            NgayDangKy = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6603),
                            TenDangNhap = "player01",
                            TrangThai = true
                        },
                        new
                        {
                            UserID = 3,
                            Email = "player02@quiz.com",
                            HoTen = "Lê Thị B",
                            MatKhau = "hashed_p2_password",
                            NgayDangKy = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6607),
                            TenDangNhap = "player02",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.PhienDangNhap", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<DateTime>("ThoiGianDangNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.HasIndex("UserID");

                    b.ToTable("PhienDangNhap", (string)null);
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.Quyen", b =>
                {
                    b.Property<int>("QuyenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuyenID"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QuyenID");

                    b.ToTable("Quyen", (string)null);

                    b.HasData(
                        new
                        {
                            QuyenID = 1,
                            MoTa = "Quản lý (Khóa/Mở khóa) tài khoản người dùng.",
                            TenQuyen = "ql_nguoi_dung"
                        },
                        new
                        {
                            QuyenID = 2,
                            MoTa = "Thêm, sửa, xóa, duyệt câu hỏi.",
                            TenQuyen = "ql_cau_hoi"
                        },
                        new
                        {
                            QuyenID = 3,
                            MoTa = "Truy cập và tạo báo cáo hệ thống.",
                            TenQuyen = "ql_baocao"
                        },
                        new
                        {
                            QuyenID = 4,
                            MoTa = "Quản lý vai trò và quyền hạn (Chỉ SuperAdmin).",
                            TenQuyen = "ql_vai_tro"
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.VaiTro", b =>
                {
                    b.Property<int>("VaiTroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaiTroID"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VaiTroID");

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            VaiTroID = 1,
                            MoTa = "Quản trị viên cấp cao, toàn quyền hệ thống.",
                            TenVaiTro = "SuperAdmin"
                        },
                        new
                        {
                            VaiTroID = 2,
                            MoTa = "Kiểm duyệt viên, quản lý câu hỏi và người dùng.",
                            TenVaiTro = "Moderator"
                        },
                        new
                        {
                            VaiTroID = 3,
                            MoTa = "Người dùng/Người chơi thông thường.",
                            TenVaiTro = "Player"
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.VaiTro_Quyen", b =>
                {
                    b.Property<int>("VaiTroID")
                        .HasColumnType("int");

                    b.Property<int>("QuyenID")
                        .HasColumnType("int");

                    b.HasKey("VaiTroID", "QuyenID");

                    b.HasIndex("QuyenID");

                    b.ToTable("VaiTro_Quyen", (string)null);

                    b.HasData(
                        new
                        {
                            VaiTroID = 1,
                            QuyenID = 1
                        },
                        new
                        {
                            VaiTroID = 1,
                            QuyenID = 2
                        },
                        new
                        {
                            VaiTroID = 1,
                            QuyenID = 3
                        },
                        new
                        {
                            VaiTroID = 1,
                            QuyenID = 4
                        },
                        new
                        {
                            VaiTroID = 2,
                            QuyenID = 1
                        },
                        new
                        {
                            VaiTroID = 2,
                            QuyenID = 2
                        },
                        new
                        {
                            VaiTroID = 2,
                            QuyenID = 3
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.CauHoi", b =>
                {
                    b.Property<int>("CauHoiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CauHoiID"));

                    b.Property<int>("ChuDeID")
                        .HasColumnType("int");

                    b.Property<string>("DapAnA")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DapAnB")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DapAnC")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DapAnD")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DapAnDung")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DoKhoID")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CauHoiID");

                    b.HasIndex("ChuDeID");

                    b.HasIndex("DoKhoID");

                    b.ToTable("CauHoi", (string)null);

                    b.HasData(
                        new
                        {
                            CauHoiID = 1,
                            ChuDeID = 1,
                            DapAnA = "Phan Đình Phùng",
                            DapAnB = "Trần Văn Thời",
                            DapAnC = "Trương Định",
                            DapAnD = "Nguyễn Trung Trực",
                            DapAnDung = "C",
                            DoKhoID = 1,
                            NgayTao = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6761),
                            NoiDung = "Ai là người phất cờ khởi nghĩa đầu tiên chống Pháp?"
                        },
                        new
                        {
                            CauHoiID = 2,
                            ChuDeID = 1,
                            DapAnA = "1953",
                            DapAnB = "1954",
                            DapAnC = "1975",
                            DapAnD = "1950",
                            DapAnDung = "B",
                            DoKhoID = 2,
                            NgayTao = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6766),
                            NoiDung = "Chiến dịch Điện Biên Phủ diễn ra năm nào?"
                        },
                        new
                        {
                            CauHoiID = 3,
                            ChuDeID = 2,
                            DapAnA = "3",
                            DapAnB = "9",
                            DapAnC = "3 và -3",
                            DapAnD = "Không có",
                            DapAnDung = "C",
                            DoKhoID = 1,
                            NgayTao = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6768),
                            NoiDung = "Căn bậc hai của 9 là bao nhiêu?"
                        },
                        new
                        {
                            CauHoiID = 4,
                            ChuDeID = 3,
                            DapAnA = "Đồng",
                            DapAnB = "Vàng",
                            DapAnC = "Nhựa",
                            DapAnD = "Bạc",
                            DapAnDung = "C",
                            DoKhoID = 2,
                            NgayTao = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6770),
                            NoiDung = "Chất nào sau đây không dẫn điện?"
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.ChuDe", b =>
                {
                    b.Property<int>("ChuDeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChuDeID"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenChuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ChuDeID");

                    b.ToTable("ChuDe", (string)null);

                    b.HasData(
                        new
                        {
                            ChuDeID = 1,
                            MoTa = "Các sự kiện và nhân vật lịch sử quan trọng.",
                            TenChuDe = "Lịch Sử Việt Nam",
                            TrangThai = true
                        },
                        new
                        {
                            ChuDeID = 2,
                            MoTa = "Các bài toán đại số và hình học cơ bản.",
                            TenChuDe = "Toán Học Phổ Thông",
                            TrangThai = true
                        },
                        new
                        {
                            ChuDeID = 3,
                            MoTa = "Kiến thức vật lý, hóa học, sinh học.",
                            TenChuDe = "Khoa Học Tự Nhiên",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.DoKho", b =>
                {
                    b.Property<int>("DoKhoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoKhoID"));

                    b.Property<int>("DiemThuong")
                        .HasColumnType("int");

                    b.Property<string>("TenDoKho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DoKhoID");

                    b.ToTable("DoKho", (string)null);

                    b.HasData(
                        new
                        {
                            DoKhoID = 1,
                            DiemThuong = 10,
                            TenDoKho = "Dễ"
                        },
                        new
                        {
                            DoKhoID = 2,
                            DiemThuong = 25,
                            TenDoKho = "Trung bình"
                        },
                        new
                        {
                            DoKhoID = 3,
                            DiemThuong = 50,
                            TenDoKho = "Khó"
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.QuizChiaSe", b =>
                {
                    b.Property<int>("QuizChiaSeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizChiaSeID"));

                    b.Property<DateTime>("NgayChiaSe")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuizTuyChinhID")
                        .HasColumnType("int");

                    b.Property<int>("UserGuiID")
                        .HasColumnType("int");

                    b.Property<int?>("UserNhanID")
                        .HasColumnType("int");

                    b.HasKey("QuizChiaSeID");

                    b.HasIndex("QuizTuyChinhID");

                    b.HasIndex("UserGuiID");

                    b.HasIndex("UserNhanID");

                    b.ToTable("QuizChiaSe", (string)null);

                    b.HasData(
                        new
                        {
                            QuizChiaSeID = 1,
                            NgayChiaSe = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(7029),
                            QuizTuyChinhID = 1,
                            UserGuiID = 2,
                            UserNhanID = 3
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.QuizNgay", b =>
                {
                    b.Property<int>("QuizNgayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizNgayID"));

                    b.Property<int?>("CauHoiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.HasKey("QuizNgayID");

                    b.HasIndex("CauHoiID");

                    b.ToTable("QuizNgay", (string)null);

                    b.HasData(
                        new
                        {
                            QuizNgayID = 1,
                            CauHoiID = 1,
                            Ngay = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.QuizTuyChinh", b =>
                {
                    b.Property<int>("QuizTuyChinhID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizTuyChinhID"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenQuiz")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("QuizTuyChinhID");

                    b.HasIndex("UserID");

                    b.ToTable("QuizTuyChinh", (string)null);

                    b.HasData(
                        new
                        {
                            QuizTuyChinhID = 1,
                            MoTa = "Các câu hỏi tôi thích nhất.",
                            NgayTao = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6954),
                            TenQuiz = "Quiz Của Tôi",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.TroGiup", b =>
                {
                    b.Property<int>("TroGiupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TroGiupID"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenTroGiup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TroGiupID");

                    b.ToTable("TroGiup", (string)null);

                    b.HasData(
                        new
                        {
                            TroGiupID = 1,
                            MoTa = "Loại bỏ hai đáp án sai.",
                            TenTroGiup = "50/50"
                        },
                        new
                        {
                            TroGiupID = 2,
                            MoTa = "Tham khảo ý kiến cộng đồng.",
                            TenTroGiup = "Hỏi khán giả"
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.CauSai", b =>
                {
                    b.Property<int>("CauSaiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CauSaiID"));

                    b.Property<int>("CauHoiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySai")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CauSaiID");

                    b.HasIndex("CauHoiID");

                    b.HasIndex("UserID");

                    b.ToTable("CauSai", (string)null);

                    b.HasData(
                        new
                        {
                            CauSaiID = 1,
                            CauHoiID = 2,
                            NgaySai = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            UserID = 3
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.ChuoiNgay", b =>
                {
                    b.Property<int>("ChuoiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChuoiID"));

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNgayLienTiep")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ChuoiID");

                    b.HasIndex("UserID");

                    b.ToTable("ChuoiNgay", (string)null);

                    b.HasData(
                        new
                        {
                            ChuoiID = 1,
                            NgayCapNhatCuoi = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6923),
                            SoNgayLienTiep = 5,
                            UserID = 2
                        },
                        new
                        {
                            ChuoiID = 2,
                            NgayCapNhatCuoi = new DateTime(2025, 11, 30, 19, 9, 0, 402, DateTimeKind.Local).AddTicks(6925),
                            SoNgayLienTiep = 2,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.KetQua", b =>
                {
                    b.Property<int>("KetQuaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KetQuaID"));

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<int>("SoCauDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongCauHoi")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiKetQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("KetQuaID");

                    b.HasIndex("UserID");

                    b.ToTable("KetQua", (string)null);

                    b.HasData(
                        new
                        {
                            KetQuaID = 1,
                            Diem = 50,
                            SoCauDung = 2,
                            ThoiGian = new DateTime(2025, 11, 30, 14, 9, 0, 402, DateTimeKind.Local).AddTicks(6797),
                            TongCauHoi = 2,
                            TrangThaiKetQua = "Hoàn thành",
                            UserID = 2
                        },
                        new
                        {
                            KetQuaID = 2,
                            Diem = 75,
                            SoCauDung = 3,
                            ThoiGian = new DateTime(2025, 11, 30, 17, 9, 0, 402, DateTimeKind.Local).AddTicks(6805),
                            TongCauHoi = 4,
                            TrangThaiKetQua = "Hoàn thành",
                            UserID = 2
                        },
                        new
                        {
                            KetQuaID = 3,
                            Diem = 25,
                            SoCauDung = 1,
                            ThoiGian = new DateTime(2025, 11, 30, 18, 9, 0, 402, DateTimeKind.Local).AddTicks(6807),
                            TongCauHoi = 2,
                            TrangThaiKetQua = "Hoàn thành",
                            UserID = 3
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.ThanhTuu", b =>
                {
                    b.Property<int>("ThanhTuuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhTuuID"));

                    b.Property<string>("AchievementCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BieuTuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DieuKien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("TenThanhTuu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThanhTuuID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("ThanhTuu", (string)null);
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.ThongKeNguoiDung", b =>
                {
                    b.Property<int>("ThongKeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThongKeID"));

                    b.Property<double>("DiemTrungBinh")
                        .HasColumnType("float");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoCauDung")
                        .HasColumnType("int");

                    b.Property<int>("SoTran")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ThongKeID");

                    b.HasIndex("UserID");

                    b.ToTable("ThongKeNguoiDung", (string)null);
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.ThuongNgay", b =>
                {
                    b.Property<int>("ThuongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThuongID"));

                    b.Property<int>("DiemThuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhanThuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiNhan")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ThuongID");

                    b.HasIndex("UserID");

                    b.ToTable("ThuongNgay", (string)null);
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.SocialRankingModels.BXH", b =>
                {
                    b.Property<int>("BXHID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BXHID"));

                    b.Property<int>("DiemThang")
                        .HasColumnType("int");

                    b.Property<int>("DiemTuan")
                        .HasColumnType("int");

                    b.Property<int>("HangThang")
                        .HasColumnType("int");

                    b.Property<int>("HangTuan")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BXHID");

                    b.HasIndex("UserID");

                    b.ToTable("BXH", (string)null);

                    b.HasData(
                        new
                        {
                            BXHID = 1,
                            DiemThang = 125,
                            DiemTuan = 125,
                            HangThang = 1,
                            HangTuan = 1,
                            UserID = 2
                        },
                        new
                        {
                            BXHID = 2,
                            DiemThang = 25,
                            DiemTuan = 25,
                            HangThang = 2,
                            HangTuan = 2,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.SocialRankingModels.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("RelatedEntityID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("UserID");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.SocialRankingModels.NguoiDungOnline", b =>
                {
                    b.Property<int>("OnlineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OnlineID"));

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OnlineID");

                    b.HasIndex("UserID");

                    b.ToTable("NguoiDungOnline", (string)null);
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.Admin", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "User")
                        .WithOne("Admin")
                        .HasForeignKey("QUIZ_GAME_WEB.Models.CoreEntities.Admin", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.VaiTro", "VaiTro")
                        .WithMany("Admins")
                        .HasForeignKey("VaiTroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.CaiDatNguoiDung", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "NguoiDung")
                        .WithOne("CaiDat")
                        .HasForeignKey("QUIZ_GAME_WEB.Models.CoreEntities.CaiDatNguoiDung", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.PhienDangNhap", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "NguoiDung")
                        .WithMany("PhienDangNhaps")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.VaiTro_Quyen", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.Quyen", "Quyen")
                        .WithMany("VaiTro_Quyens")
                        .HasForeignKey("QuyenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.VaiTro", "VaiTro")
                        .WithMany("VaiTro_Quyens")
                        .HasForeignKey("VaiTroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.CauHoi", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.QuizModels.ChuDe", "ChuDe")
                        .WithMany("CauHois")
                        .HasForeignKey("ChuDeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QUIZ_GAME_WEB.Models.QuizModels.DoKho", "DoKho")
                        .WithMany("CauHois")
                        .HasForeignKey("DoKhoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");

                    b.Navigation("DoKho");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.QuizChiaSe", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.QuizModels.QuizTuyChinh", "QuizTuyChinh")
                        .WithMany()
                        .HasForeignKey("QuizTuyChinhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "UserGui")
                        .WithMany("QuizChiaSesGui")
                        .HasForeignKey("UserGuiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "UserNhan")
                        .WithMany("QuizChiaSesNhan")
                        .HasForeignKey("UserNhanID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("QuizTuyChinh");

                    b.Navigation("UserGui");

                    b.Navigation("UserNhan");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.QuizNgay", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.QuizModels.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiID");

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.QuizTuyChinh", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "NguoiDung")
                        .WithMany("QuizTuyChinhs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.CauSai", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.QuizModels.CauHoi", "CauHoi")
                        .WithMany("CauSais")
                        .HasForeignKey("CauHoiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "NguoiDung")
                        .WithMany("CauSais")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.ChuoiNgay", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "NguoiDung")
                        .WithMany("ChuoiNgays")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.KetQua", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "User")
                        .WithMany("KetQuas")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.ThanhTuu", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.ThongKeNguoiDung", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.ResultsModels.ThuongNgay", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.SocialRankingModels.BXH", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "NguoiDung")
                        .WithMany("BXHs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.SocialRankingModels.Comment", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.SocialRankingModels.NguoiDungOnline", b =>
                {
                    b.HasOne("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungOnlines")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.NguoiDung", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("BXHs");

                    b.Navigation("CaiDat");

                    b.Navigation("CauSais");

                    b.Navigation("ChuoiNgays");

                    b.Navigation("Comments");

                    b.Navigation("KetQuas");

                    b.Navigation("NguoiDungOnlines");

                    b.Navigation("PhienDangNhaps");

                    b.Navigation("QuizChiaSesGui");

                    b.Navigation("QuizChiaSesNhan");

                    b.Navigation("QuizTuyChinhs");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.Quyen", b =>
                {
                    b.Navigation("VaiTro_Quyens");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.CoreEntities.VaiTro", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("VaiTro_Quyens");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.CauHoi", b =>
                {
                    b.Navigation("CauSais");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.ChuDe", b =>
                {
                    b.Navigation("CauHois");
                });

            modelBuilder.Entity("QUIZ_GAME_WEB.Models.QuizModels.DoKho", b =>
                {
                    b.Navigation("CauHois");
                });
#pragma warning restore 612, 618
        }
    }
}
